### PR TITLE
Fixing prog name to subsample

### PR DESCRIPTION
**Pull request by samuelleach**

### CODE REVIEW

**Comment by paulgb** [comment]
Fixed. On PyPi as version 0.0.4. Thanks Samuel.

**Comment by themiurgo** [comment]
Maybe https://pypi.python.org/pypi/sample-cli/0.0.1 should point to subsample now?

**Comment by paulgb** [comment]
It would be better if it did but I'm not sure if this is possible with PyPi since it's a past release. Probably best just to delete sample-cli

**Comment by themiurgo** [comment]
Are you still able to delete it from SourceForge? I actually discovered subsample by chance, because I was unhappy about the nameclash and investigated more. Other interested people might just stop at sample-cli obsolete package.

**Pull request merged**
